version: "3.0"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - E:\work\Workshop\RabbitMQ\docker-conf\rabbitmq\data/:/var/lib/rabbitmq/
        - E:\work\Workshop\RabbitMQ\docker-conf\rabbitmq\log/:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge